### ISSUE TITLE
Incorrectly generates local selectors when using `postcss-nested`

### ISSUE THREAD

**Issue by joepie91** [css-modules/postcss-modules-local-by-default#45]
Test case (all dependencies at latest):

```js
"use strict";

const postcss = require("postcss");

let input = `
:global {
	.foo {
		color: blue;
	}
}

:global .foo {
	color: red;
}
`;

let instance = postcss([
	require("postcss-nested"),
	// require("postcss-modules-local-by-default", { mode: "local" })
]);

instance.process(input).then((result) => {
	console.log(result.css);
});
```

Output when run as-is:

```css
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.

:global .foo {
                color: blue;
        }

:global .foo {
        color: red;
}
```

Output when uncommenting (ie. enabling) `postcss-modules-local-by-default`:

```css
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.

 :local(.foo) {
                color: blue;
        }

.foo {
        color: red;
}
```

Both selectors *should* be global selectors considering that's how they both reduce down when using `postcss-nested`, but somehow the one with block-scoped `:global` incorrectly becomes a local.

I'm not quite sure why - when disabling `postcss-modules-local-by-default` and inspecting the result AST when only `postcss-nested` is used, both nodes *appear* to be identically structured... but maybe I'm missing some PostCSS subtlety here.
