### ISSUE TITLE
The combination of a global and a local selector should be a local selector

### ISSUE THREAD

**Issue by jantimon** [css-modules/postcss-modules-local-by-default#73]
`html {  a_value: some-value; }` is not local - and therefore `css-modules/postcss-modules-local-by-default` marks them as not pure.

However if only local selectors are inside that non local selector, it is still fine as all declarations are wrapped by a local selector.
The following examples **are** pure:

```css
html { 
  .foo { 
     a_value: some-value; 
  } 
}
```

```css
html { 
 .foo { a_value: some-value; } 
 .bar { a_value: some-value; }
}
```

As soon as a non local declaration gets added it still be marked as non pure.
The following examples are **NOT** pure:

```css
html { 
 .foo { a_value: some-value; } 
 button { a_value: some-value; } 
}
```

```css
html { 
  .foo { 
     a_value: some-value; 
  } 
  color: red;
}
```

```css
html { 
 .foo { a_value: some-value; } 
 button { 
   color: red;
   .bar { a_value: some-value; }
  } 
}
```

Especially the second case will be tricky to implement in the current code as by now only the selectors are analyzed to find out wether the code is pure or not.

In future we would have to iterate over every declaration and check for its surrounding selector wether it is pure or not.

**Comment by jantimon** [comment]
I created a small next.js demo project with the following css code:

```css
.page {
  button {
    color: green;
  }
}
```

[Stackblitz without postcss-nesting](https://stackblitz.com/edit/stackblitz-starters-2twhhj?file=app%2Fpage.module.css)
without postcss-nesting `.page {  button { .. } }` is not pure:

![shot-MPwBLLsD@2x](https://github.com/user-attachments/assets/90aebfa1-51da-44f8-a4a8-898d56a99b25)

however the same css code works once you add `postcss-nesting`

[Stackblitz with postcss-nesting](https://stackblitz.com/edit/stackblitz-starters-ex9tdj?file=app%2Fpage.module.css)
![shot-mTFxVBKN@2x](https://github.com/user-attachments/assets/88b0251b-ab8c-4e8f-b70a-e16120dca310)

to align both cases I created #72 - and to proof that `.page button` I created a pr with a test case in #73
