### ISSUE TITLE
file level pure mode opt-out

### ISSUE THREAD

**Issue by jantimon** [css-modules/postcss-modules-local-by-default#84]
I got some feedback about styling third-party React components for `cssmodules-pure-ignore`

in those cases where you need `/* cssmodules-pure-ignore */` very often you need it several times e.g. when styling over an external library:

```css
/* cssmodules-pure-ignore */
:global(.select__control) { border: 1px solid #e2e8f0 }

/* cssmodules-pure-ignore */
:global(.select__menu) { box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1) }

/* cssmodules-pure-ignore */
:global(.select__option--is-selected) { background: #4299e1 }

/* and so on... */
```

and for `postcss-nested` it's even worse as every `&` selector (e.g. `&:hover`) must have its own ignore comment..

what do you think about adding a `cssmodules-pure-no-check` flag that can be placed at the file root to disable pure mode for the entire file:

```css
/* cssmodules-pure-no-check */

:global(.select__control) { border: 1px solid #e2e8f0 }
:global(.select__menu) { box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1) }
:global(.select__option--is-selected) { background: #4299e1 }
```

I'll add a small pr so maybe looking at it helps to understand the idea
